### ISSUE TITLE
Woodrow Wilson School of Public and International Affairs Should Change?

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/repecwp#33]
The seed data has Woodrow Wilson School in it https://github.com/pulibrary/repecwp/blob/6244544e3848ebfb8371a23ede4c47534bfd824c/db/series_seeds.csv

Should it change to Princeton School of Public and International Affairs (SPIA)

This application is comprised of series and this is one of those series. Ask Bobray if this will cause any problems.

**Comment by kevinreiss** [comment]
I asked bobray about this today.

**Comment by kevinreiss** [comment]
Bobray's response.

"That was the title.  Renaming would make unfindable when one has a reference."
